apiVersion: apps/v1
kind: Deployment
metadata:
  name: t53gtregt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t53gtregt
  template:
    metadata:
      labels:
        app: t53gtregt
    spec:
      containers:
      - image: okteto.dev/t53gtregt:latest
        name: t53gtregt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "animelst.com"
        - name: Vless_UUID
          value: "5ab512f0-644f-4093-b974-20fe029ac1c3"
        - name: Vless_Path
          value: "/76hyttg"
        - name: Vmess_UUID
          value: "5ab512f0-644f-4093-b974-20fe029ac1c3"
        - name: Vmess_Path
          value: "/fevx"
        - name: Share_Path
          value: "/share233"
