apiVersion: v1
kind: Service
metadata:
  name: t53gtregt
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "t53gtregt"
    port: 8080
  selector:
    app: t53gtregt
